const state={cancelId:null,queueAhead:4};
const $=id=>document.getElementById(id);
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2500)}
function showPage(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('pageTitle').textContent={dashboard:'Good morning, Student!',appointments:'My Appointments',queue:'Live Queue',profile:'My Profile'}[page];if(page==='appointments')renderAppointments();window.scrollTo(0,0)}
document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>showPage(x.dataset.page));
function openModal(id){$(id).classList.add('show')}function closeModal(id){$(id).classList.remove('show')}
document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>closeModal(x.dataset.close));
$('heroBook').onclick=$('quickBook').onclick=$('newAppointment').onclick=()=>openModal('bookingModal');
const d=new Date();d.setDate(d.getDate()+1);$('date').min=d.toISOString().slice(0,10);
$('bookingForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;b.textContent='Booking…';const r=await ClinicAPI.createAppointment({service:$('service').value,date:$('date').value,time:$('time').value});$('dashQueue').textContent=r.queueNumber;$('queueNumber').textContent=r.queueNumber;state.queueAhead=5;$('dashAhead').textContent=5;$('queueAhead').textContent=5;$('bookingFeedback').hidden=false;toast('Appointment booked successfully.');setTimeout(()=>{b.disabled=false;b.textContent='Confirm Appointment';$('bookingFeedback').hidden=true;closeModal('bookingModal');showPage('appointments')},900)};
async function renderAppointments(){const l=$('appointmentList');l.innerHTML='<div class="card" style="padding:22px;color:#667572">Loading appointments…</div>';const a=await ClinicAPI.getAppointments();l.innerHTML=a.map(x=>`<article class="appointment-card card"><div class="date-box"><b>${x.date}</b><small>${x.month}</small></div><div class="appointment-details"><b>${x.service}</b><p>${x.doctor} · ${x.time}</p></div><span class="badge confirmed">${x.status}</span><button class="btn danger cancel-btn" data-id="${x.id}">Cancel</button></article>`).join('');document.querySelectorAll('.cancel-btn').forEach(b=>b.onclick=()=>{state.cancelId=b.dataset.id;openModal('deleteModal')})}
$('confirmCancel').onclick=async()=>{const b=$('confirmCancel');b.disabled=true;b.textContent='Cancelling…';await ClinicAPI.cancelAppointment(state.cancelId);closeModal('deleteModal');b.disabled=false;b.textContent='Yes, Cancel';toast('Appointment cancelled. The slot is now available.');renderAppointments()};
$('profileForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;b.textContent='Saving…';await ClinicAPI.saveProfile({name:$('fullName').value});$('profileFeedback').hidden=false;toast('Profile changes saved.');setTimeout(()=>{b.disabled=false;b.textContent='Save Changes';$('profileFeedback').hidden=true},1800)};
$('logoutBtn').onclick=()=>openModal('logoutModal');$('confirmLogout').onclick=()=>{closeModal('logoutModal');toast('You have been signed out.')};
setInterval(()=>{if(state.queueAhead>0&&Math.random()>.45){state.queueAhead--;$('dashAhead').textContent=state.queueAhead;$('queueAhead').textContent=state.queueAhead;$('queueWait').textContent=state.queueAhead?'~'+state.queueAhead*6+' min':'Now';$('queueProgress').style.width=(72+(4-state.queueAhead)*6)+'%';if(!state.queueAhead)toast('You are next! Please proceed to the clinic.')}},15000);
renderAppointments();